# -*- coding: utf-8 -*-
"""
/***************************************************************************
 cadastral_classifier
                                 A QGIS plugin
 cadastral_classifier
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-07-22
        copyright            : (C) 2021 by yo
        email                : 1
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load cadastral_classifier class from file cadastral_classifier.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cadastral_classifier import cadastral_classifier
    return cadastral_classifier(iface)
