theme: jekyll-theme-minimal
title: Cadastral Classifier Homepage
permalink: https://github.com/TransUrban-UAH/Cadastral_Classifier
logo: https://github.com/TransUrban-UAH/Cadastral_Classifier/blob/main/icon.jpg
